services:

  app:
    container_name: auto-gameplay-app
    build:
      context: .
    user: root
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8000:8000
    volumes:
      - ./:/app
      - ./data/DB/pgbackups:/backups
    networks:
      - auto-gameplay

  pgadmin:
    container_name: auto-gameplay-pgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_FILE_UPLOAD_MAX_MEMORY_SIZE: 52428800000  # 500MB
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - auto-gameplay

  db:
    container_name: auto-gameplay-db
    image: postgres:alpine
    restart: unless-stopped
    user: postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:${DB_PORT}
    expose:
      - ${DB_PORT}
    volumes:
      - ./data/DB/pgbackups:/backups
      - db-data:/var/lib/postgresql/data
    networks:
      - auto-gameplay
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 5s
      timeout: 3s
      retries: 5

  backup:
    container_name: auto-gameplay-backup
    image: postgres:alpine
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    entrypoint: >
      sh -c "apk add --no-cache gzip tar && while true; do PGPASSWORD=$$POSTGRES_PASSWORD pg_dump -h db -U $$POSTGRES_USER $$POSTGRES_DB > /tmp/backup-\$(date +%Y-%m-%d).sql && tar -czf /backups/backup-\$(date +%Y-%m-%d).tar.gz -C /tmp backup-\$(date +%Y-%m-%d).sql && rm /tmp/backup-\$(date +%Y-%m-%d).sql; sleep 86400; done"
    volumes:
      - ./data/DB/pgbackups:/backups
    networks:
      - auto-gameplay

networks:
  auto-gameplay:

volumes:
  db-data:
  pgadmin-data:

